FROM --platform=x86-64 linuxserver/webtop:ubuntu-xfce

ENV PUID=1000 
ENV PGID=1000
ENV TZ=Etc/UTC 

EXPOSE 3000
EXPOSE 3001

# Initialize misc
USER root
RUN apt update
RUN apt install git -y
RUN apt install wget -y
RUN apt install openjdk-21-jdk -y
RUN apt install psmisc -y
RUN apt install nano -y
RUN apt install build-essential -y

# Install ProbLog
USER root
RUN apt install -y python3
RUN apt install -y python3-pip
RUN pip install --break-system-packages problog
RUN pip install --break-system-packages PySDD

# Install eclipse
USER root
RUN wget 'https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2024-03/R/eclipse-modeling-2024-03-R-linux-gtk-x86_64.tar.gz&r=1' -O eclipse.tar.gz
RUN tar -xzf eclipse.tar.gz -C /opt
RUN rm eclipse.tar.gz
RUN echo '[Desktop Entry]\n\
Version=13.0\n\
Type=Application\n\
Terminal=false\n\
Icon=/opt/eclipse/icon.xpm\n\
Name=Modeling 2024-03\n\
Exec=/opt/eclipse/eclipse\n\
Name=Modeling 2024-03\n\
Categories=Development\n\' > /usr/share/applications/eclipse.desktop

# Install VIATRA and dependencies
USER root
RUN /opt/eclipse/eclipse -application org.eclipse.equinox.p2.director -repository https://download.eclipse.org/releases/2024-03 -installIU org.eclipse.collections.feature.source.feature.group/11.1.0.v20220705-1455,org.eclipse.xtend.sdk.feature.group/2.34.0.v20240227-0940,org.eclipse.xtext.redist.feature.group/0.0.0
RUN /opt/eclipse/eclipse -application org.eclipse.equinox.p2.director -repository http://download.eclipse.org/viatra/updates/release/2.8.0 -installIU org.eclipse.viatra.query.sdk.feature.source.feature.group/2.8.0.202310201322,org.eclipse.viatra.query.sdk.feature.feature.group/2.8.0.202310201322